### ISSUE TITLE
Ajout d'une licence

### ISSUE THREAD

**Issue by bzg** [betagouv/DNC#4]
Bravo pour cette ouverture et à votre disposition pour aider à trouver la bonne licence parmi [celles autorisées](https://www.data.gouv.fr/fr/licences).

**Comment by bzg** [comment]
Bonjour, je me permets de revenir vers vous concernant la question de la licence : ce dépôt risque d'être largement exposé dans le cadre des engagements du MFTP sur les ouvertures de code source, il faudrait que cette issue puisse être résolue rapidement.  A votre disposition pour aider si besoin.

**Comment by kmonlouis** [comment]
Bonjour, Normalement la licence a été ajouté avec une des licences autorisées avec ce commit 2e6ad48ca032b2ec7d786919b75af70ddd7f0015 malgré une erreur sur le numéro d'issue dans le message de commit.

**Comment by bzg** [comment]
Super, merci beaucoup !  Je ferme l'issue.
